// ─── Static Data ──────────────────────────────────────────────────────────────
export const movie = {
  id: 1,
  movieId: 101,
  title: "Vikram",
  release_date: "2022-06-03",
  duration_minutes: 174,
  language: ["Tamil", "Telugu", "Hindi"],
  industry: "Kollywood",
  rating: 8.4,
  poster_url: null,
  plot: {
    short:
      "Three timelines collide as a retired black-ops agent resurfaces to dismantle a brutal drug cartel.",
    full: "DSP Amar investigates a series of killings targeting narcotics officers by a masked vigilante group. Retired cop Karnan is drawn back into the underworld after his son's murder. The ghost operative Vikram re-emerges from the shadows — connecting a decades-old conspiracy across three generations.",
  },
  characters: [
    {
      id: "c1",
      name: "Amar",
      role: "Protagonist",
      actor: { name: "Fahadh Faasil" },
    },
    {
      id: "c2",
      name: "Karnan",
      role: "Protagonist",
      actor: { name: "Vijay Sethupathi" },
    },
    {
      id: "c3",
      name: "Pradeep",
      role: "Supporting",
      actor: { name: "Kalidas Jayaram" },
    },
    {
      id: "c4",
      name: "Rolex",
      role: "Antagonist",
      actor: { name: "Vijay Sethupathi" },
    },
    {
      id: "c5",
      name: "Santham",
      role: "Supporting",
      actor: { name: "Antony Varghese" },
    },
    {
      id: "c6",
      name: "Vikram",
      role: "Protagonist",
      actor: { name: "Kamal Haasan" },
    },
  ],
  timelines: [
    {
      id: "t1",
      title: "Cold open",
      type: "action",
      sequence_order: 1,
      start_time: 0,
      end_time: 8,
      location_name: "Chennai",
      emotion_type: "tense",
      is_twist: false,
      is_climax: false,
      is_flashback: false,
      importance_score: 7,
      description:
        "DSP Amar leads a brutal narcotics bust. A masked outfit wipes out the entire team — leaving zero survivors.",
      famous_dialogue:
        "I will say what I have to say once; I won't repeat it a second time.",
      characters_involved: [
        { id: "c1", name: "Amar" },
        { id: "c2", name: "Karnan" },
      ],
    },
    {
      id: "t2",
      title: "Karnan's intro",
      type: "drama",
      sequence_order: 2,
      start_time: 8,
      end_time: 22,
      location_name: "Chennai suburbs",
      emotion_type: "intense",
      is_twist: false,
      is_climax: false,
      is_flashback: false,
      importance_score: 8,
      description:
        "Retired cop Karnan lives quietly with his family, hiding a dangerous past. His son Pradeep pulls him back into chaos.",
      famous_dialogue: "I have received my pension. The old story is over.",
      characters_involved: [
        { id: "c2", name: "Karnan" },
        { id: "c3", name: "Pradeep" },
      ],
    },
    {
      id: "t3",
      title: "Rolex revealed",
      type: "action",
      sequence_order: 3,
      start_time: 22,
      end_time: 40,
      location_name: "Warehouse district",
      emotion_type: "intense",
      is_twist: true,
      is_climax: false,
      is_flashback: false,
      importance_score: 9,
      description:
        "The drug kingpin Rolex makes his grand entrance — brutally establishing dominance over his cartel network.",
      famous_dialogue:
        "No one is a hero here, and no one is even a villain. Here, money is the only thing that matters.",
      characters_involved: [
        { id: "c4", name: "Rolex" },
        { id: "c5", name: "Santham" },
      ],
    },
    {
      id: "t4",
      title: "Pradeep's death",
      type: "drama",
      sequence_order: 4,
      start_time: 40,
      end_time: 55,
      location_name: "Highway",
      emotion_type: "sad",
      is_twist: false,
      is_climax: false,
      is_flashback: false,
      importance_score: 9,
      description:
        "Karnan's son Pradeep is killed in a cartel ambush, awakening the beast within Karnan.",
      famous_dialogue: "Father... I made a mistake.",
      characters_involved: [
        { id: "c2", name: "Karnan" },
        { id: "c3", name: "Pradeep" },
      ],
    },
    {
      id: "t5",
      title: "Vikram emerges",
      type: "action",
      sequence_order: 5,
      start_time: 80,
      end_time: 90,
      location_name: "Rooftop, Chennai",
      emotion_type: "intense",
      is_twist: true,
      is_climax: false,
      is_flashback: false,
      importance_score: 10,
      description:
        "The ghost operative VIKRAM resurfaces after decades. His true identity stuns everyone — including the audience.",
      famous_dialogue: "I am Vikram. There is no retirement for me.",
      characters_involved: [
        { id: "c6", name: "Vikram" },
        { id: "c1", name: "Amar" },
        { id: "c4", name: "Rolex" },
      ],
    },
    {
      id: "t6",
      title: "Flashback — origin",
      type: "flashback",
      sequence_order: 6,
      start_time: 90,
      end_time: 110,
      location_name: "1980s Chennai",
      emotion_type: "nostalgic",
      is_twist: false,
      is_climax: false,
      is_flashback: true,
      importance_score: 8,
      description:
        "We see young Karnan's first encounter with the Vikram programme — a covert black-ops unit that wipes its own agents.",
      famous_dialogue:
        "One who does not know how to face death cannot truly live.",
      characters_involved: [
        { id: "c2", name: "Karnan" },
        { id: "c6", name: "Vikram" },
      ],
    },
    {
      id: "t7",
      title: "Comedy track",
      type: "comedy",
      sequence_order: 7,
      start_time: 55,
      end_time: 72,
      location_name: "Amar's home",
      emotion_type: "humorous",
      is_twist: false,
      is_climax: false,
      is_flashback: false,
      importance_score: 5,
      description:
        "Amar's domestic chaos provides comic relief — his wife and in-laws blissfully unaware of the war outside.",
      famous_dialogue: "Oh God, can you cook using your gun?",
      characters_involved: [{ id: "c1", name: "Amar" }],
    },
    {
      id: "t8",
      title: "Rolex vs Vikram",
      type: "action",
      sequence_order: 8,
      start_time: 130,
      end_time: 148,
      location_name: "Chemical plant",
      emotion_type: "intense",
      is_twist: false,
      is_climax: false,
      is_flashback: false,
      importance_score: 10,
      description:
        "Vikram and Rolex finally clash in a devastating hand-to-hand showdown. Both men are gravely wounded.",
      famous_dialogue:
        "There are a thousand people like you, but there is no one else like you.",
      characters_involved: [
        { id: "c6", name: "Vikram" },
        { id: "c4", name: "Rolex" },
      ],
    },
    {
      id: "t9",
      title: "Grandfather twist",
      type: "drama",
      sequence_order: 9,
      start_time: 148,
      end_time: 160,
      location_name: "Hospital",
      emotion_type: "intense",
      is_twist: true,
      is_climax: false,
      is_flashback: false,
      importance_score: 10,
      description:
        "The true connection between Karnan, Vikram, and Pradeep is revealed — a three-generation secret that reframes everything.",
      famous_dialogue: "You are his son... I have been searching for you.",
      characters_involved: [
        { id: "c2", name: "Karnan" },
        { id: "c6", name: "Vikram" },
        { id: "c3", name: "Pradeep" },
      ],
    },
    {
      id: "t10",
      title: "Climax",
      type: "climax",
      sequence_order: 10,
      start_time: 160,
      end_time: 174,
      location_name: "Rooftop, night",
      emotion_type: "intense",
      is_twist: false,
      is_climax: true,
      is_flashback: false,
      importance_score: 10,
      description:
        "Karnan sacrifices himself to destroy Rolex and the cartel. The Vikram legacy lives on through a new generation.",
      famous_dialogue: "The Vikram programme will never end.",
      characters_involved: [
        { id: "c2", name: "Karnan" },
        { id: "c4", name: "Rolex" },
        { id: "c6", name: "Vikram" },
      ],
    },
  ],
};
