name: Deploy to CPanel

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Deploy Files to CPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Port 21 (Plain FTP) work aagala na, indha 2 lines-ai add pannunga
          # port: 22

          # GitHub repo-la backend folder
          local-dir: ./backend/

          # CPanel Application Root
          server-dir: /nextshow_backend_v2/

          # .env upload aaga koodathu
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/.env
            **/node_modules/**
            **/README.md
